### ISSUE TITLE
3.6 - Lot's of TODO's

### ISSUE THREAD

**Issue by azidar** [ucb-bar/generator-bootcamp#29]
- [] getVerilog is passed a () => Module instead of Module
- [] No description about the `@` sign in a match/case statement.
- [] SomeGeneratorParameters is not defined.

**Comment by edwardcwang** [comment]
1) In most cases one should call `chiselTypeOf(...)` instead of `.cloneType()`

2) If you don't care about the output's width explicitly one option could just be `new Mac(chiselTypeOf(a), UInt())`?

**Comment by lmy441900** [comment]
~~Lot's of TODO's~~ Lots of TODOs: I think this issue should be pinned on top and be tagged with help-wanted.

Just now I went through 3.6. The good point is that I have some knowledge on functional programming languages, and many of the features in Scala seem natural to me; however for newbies they are hard to understand. Many places are not refined, and I even find that the "Exercise: Integrator" has been filled with the provided solution, which cannot pass compilation. Solution for 3.6 "Exercise: Mac as Object" (as mentioned by @gsomlo) is also broken.

I'm also new to Chisel and so far I don't have the ability to fix them though...
